pesto-students/batch-10-tripen

.circleci/config.yml

Build: circleci initial setup

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

setup: add PR and Issue templates

---

client/.gitignore

setup: ignore package-lock.json and all .log files

---

.eslintignore
.eslintrc.json
client/package.json
package.json

eslint prettier husky setup in the root directory
fixes: #3

build: setup eslint, husky

---

server/src/controllers/posts.js
server/src/models/category.js
server/src/models/post.js
server/src/models/timeline.js
server/src/models/user.js
yarn.lock

define schema for user, timeline, post and category
models.
#

feat: add mongoose schemas in server/models

---

.circleci/config.yml

build: edit config.yml

---

client/src/components/App.jsx

fix: routes with switch ids & default path

---

server/src/controllers/posts.js
server/src/controllers/timeline.js
server/yarn.lock

add posts controllers

---

client/src/components/App.jsx
client/src/components/organisms/Header/Header.jsx
client/src/components/organisms/PrivateRoute/PrivateRoute.jsx
client/src/components/organisms/TripList/TripList.jsx
client/src/components/pages/HomePage/HomePage.jsx
client/src/index.js

feat: Private Routes

---

client/src/components/atoms/CardDatePicker/CardDatePicker.jsx
client/src/components/atoms/CardTimeDisplay/CardTimeDisplay.jsx
client/src/components/molecules/TimeLineCard/TimeContext.jsx
client/src/components/molecules/TimeLineCard/TimeLineCard.jsx

TimeLineCard context resolved

---

client/package.json
client/src/components/pages/HomePage/HomePage.jsx
client/src/components/pages/HomePage/getFeaturedTimelines.js
client/src/components/pages/TimeLinePage/TimeLinePage.jsx
client/src/components/pages/TimeLinePage/getTimelineDetails.js
client/yarn.lock
package.json
yarn.lock

fix:axios get functions

---

client/src/components/App.jsx
client/src/components/organisms/CoverImage/CoverImage.jsx
client/src/components/organisms/PrivateRoute/PrivateRoute.jsx
client/src/components/organisms/TimeLine/TimeLine.jsx
client/src/components/pages/TimeLinePage/TimeLinePage.jsx
client/src/components/pages/TimeLinePage/postTimelineDetails.js

edit timeline

---

server/src/controllers/timeline.js

fix: update timeline

---

client/src/components/organisms/CoverImage/CoverImage.jsx
client/src/components/pages/TimeLinePage/TimeLinePage.jsx
client/src/components/pages/TimeLinePage/postTimelineDetails.js
server/src/configs/server.js

working CORS added method put

---

server/src/configs/server.js
server/src/routes/api/index.js
server/src/routes/api/v1/auth.js
server/src/routes/api/v1/categories.js
server/src/routes/api/v1/index.js
server/src/routes/api/v1/index.test.js
server/src/routes/api/v1/timeline.js
server/src/routes/api/v1/user.js
server/src/routes/index.js
server/yarn.lock

add routes for auth, user, timeline, categories
fix: #28
( To setup routes quick for everyone to start work, will push routes tests in next PR )
#28
Routes for auth, user, timeline and categories functioning

feat: add server routes

---

client/src/components/App.jsx
client/src/components/organisms/TimeLine/TimeLine.jsx

working proj

---

.circleci/config.yml
client/package.json
client/yarn.lock

fix: #54
#54 
Installs jest and other dependencies which were added later on circleci before running tests.

fix: remove --frozen-lockfile and add updated yarn.lock

---

server/src/controllers/timeline.js
server/src/controllers/timeline.test.js
server/src/middlewares/printRoute.js
server/src/routes/api/v1/timeline.js
server/src/routes/index.js

feat-middleware print, cntl setup

---

package.json

fix #73
#73 
every commit would be linted before hand
Changes are done in Line 18,22

fix: updated faulty eslint commands in package.json

---

client/src/components/README.md
client/src/components/atoms/README.md
client/src/components/molecules/README.md
client/src/components/organisms/README.md
client/src/components/pages/README.md
client/src/components/templates/README.md
package.json
server/package.json
server/src/configs/database.js
server/src/configs/dbtest.js
server/src/controllers/timeline.js
server/src/controllers/timeline.test.js
server/src/middlewares/printRoute.js
server/src/models/category.js
server/src/models/post.js
server/src/models/timeline.js
server/src/models/user.js
server/src/routes/api/v1/timeline.js
server/src/routes/index.js
server/yarn.lock

setup - db connect, models initialized

---

client/package.json
client/src/components/App.jsx
client/src/components/molecules/PrivateRoute.jsx
client/src/components/pages/Profile/index.jsx
client/yarn.lock

Adds Routes
#
has more detailed & private routes

feat: Private Routes and other Routes

---

client/package.json
client/yarn-error.log

#93 
Sets a proxy URL that will be used while developing so that you don't have redundant URL origins when we deploy your website to the public
Now, instead of making HTTP requests like this:
`axios.get("http://localhost:8080/example")`
We should write them like this:
`axios.get("/example")`

feat-proxy in react "package.json"

---

server/.babelrc
server/package.json
server/src/middlewares/README.md
server/src/middlewares/timeline.js
server/src/middlewares/timeline.test.js
server/src/models/timeline.js
server/src/routes/api/v1/timeline.js
server/yarn.lock

feat:middleware timeline

---

client/package.json
client/src/components/App.jsx
client/src/components/organisms/Header/Header.jsx
client/src/components/organisms/LoginModal/LoginModal.jsx
client/src/components/pages/NotFound/NotFound.jsx
client/yarn.lock

added 404 page
updated route for 404 page
added font awesome
beautified header using font awesome
refactored signUpToggle function
#91 
Redirects user to a dedicated page in case of a 404 error.

added 404 page

---

server/src/models/timeline.js

#
mongodb model validation for required fields.
removing required field, due to default value = false;
usage of required and default applies redundant rule on
the given field.

fix:update timeline model

---

server/src/middlewares/README.md
server/src/middlewares/timeline.js
server/src/middlewares/timeline.test.js
server/src/models/timeline.js
server/src/routes/api/v1/timeline.js

#
new middleware to validate timeline subdoc posts

feat: modify route, new validations, test files

---

client/src/component/AuthorTimelines/AuthorTimelines.test.jsx
client/src/component/LoadingIndicator/index.jsx
client/src/component/TimelineCard/TimelineCard.test.jsx
client/src/component/TimelineCard/index.jsx
client/src/component/TimelineList/TimelineList.test.jsx
client/src/component/TimelineList/index.jsx
client/src/components/App.jsx
client/src/containers/Home/fetchTimelines.js
client/src/containers/Home/index.jsx
client/src/utils/getLastUpdatedTime.js
client/src/views/Home.jsx
client/src/views/HomeView.test.jsx

fix: #103
Adds Clickable Timeline Cards, and Loading Indicator
#103

chore: Fix and Home Page and Trending timelines

---

server/src/controllers/v1/timeline.js
server/src/controllers/v1/timeline.test.js
server/src/daos/timeline.js
server/src/middlewares/auth.js
server/src/middlewares/timeline.js
server/src/routes/api/v1/timeline.js

fetch timeline by userid and jwt
#115

chore-fetch timelines by user cntl,route,dao

---

server/src/controllers/v1/timeline.js
server/src/daos/timeline.js
server/src/middlewares/auth.js
server/src/middlewares/timeline.test.js
server/src/routes/api/v1/timeline.js

fix: #120
#120
GIF of user timelines fetch ( by public / private modifiers) functionality:

fix: /timeline/all/:userid GET functionality

---

server/src/models/category.js
server/src/models/post.js
server/src/models/timeline.js
server/src/models/user.js
server/src/utils/validations/signup.js

- remove signup location validations
fix: 119
#119 
{
location: {
name: String,
coordinates: [Number]
}

fix: change location property from geoJSON to string

---

client/src/components/molecules/SignInDetails/SignInDetails.jsx
client/src/components/molecules/SignUpDetails/SignUpDetails.jsx

#108 
Forms are being validated

feat: frontend validations for sign up & login-form.

---

client/src/containers/Home/fetchTimelines.js

fix: #133
#133 
now fetches home page timelines from server

chore: homepage server integration

---

client/src/components/molecules/SignInDetails/SignInDetails.jsx

sign in fix

---

server/src/controllers/v1/user.js
server/src/daos/timeline.js

feat-update user token on update

---

client/src/component/AuthorInfoSection/AuthorInfoSection.test.jsx
client/src/component/AuthorTimelines/AuthorTimelines.test.jsx
client/src/containers/Home/fetchTimelines.js
client/src/views/Profile.jsx
client/src/views/ProfileView.test.jsx

passing client tests

---

server/src/controllers/v1/timeline.test.js
server/src/daos/timeline.js
server/src/routes/api/v1/timeline.js

fix:test files changed, timeline delete msg

---

server/src/routes/api/v1/timeline.js

bugfix:revert middleware in timeline delete

---

server/src/controllers/v1/timeline.test.js
server/src/daos/timeline.js
server/src/routes/api/v1/timeline.js

fix: revert timeline delete middleware to check user permission

---

server/src/controllers/v1/auth.test.js
server/src/controllers/v1/user.js
server/src/middlewares/user.js
server/src/models/user.js
server/src/routes/api/v1/user.js
server/src/utils/helpers/jwtHelper.js

- add 'remove' pre hook for deleting documents
when a user gets deleted.
fix: #145
#

feat: update and refac user controllers

---

server/src/daos/timeline.js
server/src/models/timeline.js

feat: change default img url, getall timelines

---

client/src/component/TimelineList/index.jsx
client/src/components/App.jsx
client/src/components/molecules/SignUpDetails/SignUpDetails.jsx
client/src/components/organisms/CoverImage/CoverImage.jsx
client/src/components/organisms/Header/Header.jsx
client/src/components/organisms/TimeLine/Post.jsx
client/src/components/organisms/TimeLine/TimeLine.jsx
client/src/components/pages/TimeLinePage/EditButton.jsx
client/src/components/pages/TimeLinePage/EditTimeLine.jsx
client/src/components/pages/TimeLinePage/PostContext.jsx
client/src/components/pages/TimeLinePage/TimeLinePage.jsx
client/src/context/timeline/timelineReducer.js
client/src/context/timeline/timelineState.jsx
client/src/context/types.js

[WIP]Create and Edit Timelines

---

client/src/components/pages/TimeLinePage/EditTimeLine.jsx

toggle timeline private

---

client/src/containers/Home/fetchTimelines.js
client/src/containers/Home/index.jsx
client/src/views/Home.jsx
server/src/controllers/v1/timeline.js
server/src/daos/timeline.js
server/src/models/timeline.js

feat - paginate homepage

---

server/src/controllers/v1/timeline.js
server/src/daos/timeline.js
server/src/models/post.js
server/src/models/timeline.js
server/src/routes/api/v1/index.js
server/src/routes/api/v1/post.js
server/src/routes/api/v1/timeline.js

feat: add /post api

---

server/src/utils/constants.js

fix-get isprivate from tomeline

---

client/src/components/atoms/LogoutButton/LogoutButton.jsx
client/src/components/organisms/Header/Header.jsx
server/src/daos/timeline.js

fix frontend logout, fetch timelineById with user

---

client/src/components/organisms/CoverImage/CoverImage.jsx
client/src/components/pages/TimeLinePage/TimeLinePage.jsx

author link

---

server/src/models/timeline.js

fix models

---

client/src/components/organisms/CoverImage/CoverImage.jsx

title view
